# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/me-and/nix-index-database/releases/download/2025-06-30-054414/index-";
  hashes = {
    x86_64-linux = "sha256-nS77cKyoNaciBxt6PWeQ/LNILa+H5XuQnTt5CbzRZms=";
    aarch64-linux = "sha256-4ZRIY+zukI8/TOX7vyHu2TTANEcL4e3Dyd/207rJbuo=";
    x86_64-darwin = "sha256-/aiSDao7KZRi2Ln76GPVNzkwg+n1Yp/ofXUWKdogSGY=";
    aarch64-darwin = "sha256-EJzYV6jV4EOECiw734jh9ohc8yyNCjDK9iLxPyZGebw=";
  };
}
