# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/me-and/nix-index-database/releases/download/2025-09-15-053925/index-";
  hashes = {
    x86_64-linux = "sha256-Ld6uQw+E0w32empaqH/kiRyorO4yvbWOswtQubMj60o=";
    aarch64-linux = "sha256-Vl9AwbLLy+fKH9rC7wLDnALj4hTQY7Lr8ie80ftvb6k=";
    x86_64-darwin = "sha256-UftSVSGF6SLeHuvp0aQE1AvBS/x167w5n67FLDqcxgM=";
    aarch64-darwin = "sha256-9htDAWEysxtjnvPzzBq13tWvqKTYrYRkCdQImcnwkyI=";
  };
}
