# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/me-and/nix-index-database/releases/download/2026-02-16-063844/index-";
  hashes = {
    x86_64-linux = "sha256-/rYoNaO79Mgkcg47P5O2+3IGwtin9SyIE7mk/zdNxkI=";
    aarch64-linux = "sha256-xIsDfpIRis9js+zDuGf6Hb5bJoL/avKonJnC8NdZ/ug=";
    x86_64-darwin = "sha256-JRHwURPkBkAEKPuG4hObzVuWJ+eTCZ34gcucExWMh5M=";
    aarch64-darwin = "sha256-6etk9Ou/dy+S6WkstW10OaUIAvmOqdSIJra4ak5dDiI=";
  };
}
